### ISSUE TITLE
bug in pre-release

### ISSUE THREAD

**Issue by Mathadon** [pallets/markupsafe#118]
Somehow pip tried to install the pre-release just now on my pc instead of grabbing a stable release. Not sure whether that's intentional but I get the following error when doing so:

```Installed /usr/local/lib/python3.5/dist-packages/future-0.18.2-py3.5.egg
Searching for MarkupSafe>=1.1
Reading https://pypi.org/simple/MarkupSafe/
Downloading https://files.pythonhosted.org/packages/e0/bf/acc45baeb2d7333ed724c30af188640d9cb0be4b28533edfc3e2ae5aad72/MarkupSafe-2.0.0a1.tar.gz#sha256=beac28ed60c8e838301226a7a85841d0af2068eba2dcb1a58c2d32d6c05e440e
Best match: MarkupSafe 2.0.0a1
Processing MarkupSafe-2.0.0a1.tar.gz
Writing /tmp/easy_install-hkxttng2/MarkupSafe-2.0.0a1/setup.cfg
Running MarkupSafe-2.0.0a1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-hkxttng2/MarkupSafe-2.0.0a1/egg-dist-tmp-s5xf4p4g
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-hkxttng2/MarkupSafe-2.0.0a1/setup.py", line 56, in <module>
    'buildingspy/thirdParty.dymat',
  File "/tmp/easy_install-hkxttng2/MarkupSafe-2.0.0a1/setup.py", line 43, in run_setup
    'simplejson',
  File "/usr/local/lib/python3.5/dist-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.5/distutils/core.py", line 121, in setup
    dist.parse_config_files()
  File "/usr/local/lib/python3.5/dist-packages/setuptools/dist.py", line 690, in parse_config_files
    ignore_option_errors=ignore_option_errors)
  File "/usr/local/lib/python3.5/dist-packages/setuptools/config.py", line 121, in parse_configuration
    meta.parse()
  File "/usr/local/lib/python3.5/dist-packages/setuptools/config.py", line 426, in parse
    section_parser_method(section_options)
  File "/usr/local/lib/python3.5/dist-packages/setuptools/config.py", line 399, in parse_section
    self[name] = value
  File "/usr/local/lib/python3.5/dist-packages/setuptools/config.py", line 184, in __setitem__
    value = parser(value)
  File "/usr/local/lib/python3.5/dist-packages/setuptools/config.py", line 515, in _parse_version
    version = self._parse_attr(value, self.package_dir)
  File "/usr/local/lib/python3.5/dist-packages/setuptools/config.py", line 349, in _parse_attr
    module = import_module(module_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 669, in exec_module
  File "<frozen importlib._bootstrap_external>", line 775, in get_code
  File "<frozen importlib._bootstrap_external>", line 735, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/tmp/easy_install-hkxttng2/MarkupSafe-2.0.0a1/src/markupsafe/__init__.py", line 83
    return f"{self.__class__.__name__}({super().__repr__()})"
                                                            ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 74, in <module>
    "Topic :: Utilities",
  File "/usr/local/lib/python3.5/dist-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.5/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/local/lib/python3.5/dist-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run(show_deprecation=False)
  File "/usr/local/lib/python3.5/dist-packages/setuptools/command/easy_install.py", line 425, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/local/lib/python3.5/dist-packages/setuptools/command/easy_install.py", line 674, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/local/lib/python3.5/dist-packages/setuptools/command/easy_install.py", line 721, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/local/lib/python3.5/dist-packages/setuptools/command/easy_install.py", line 766, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 783, in resolve
    replace_conflicting=replace_conflicting
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 1066, in best_match
    return self.obtain(req, installer)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 1078, in obtain
    return installer(requirement)
  File "/usr/local/lib/python3.5/dist-packages/setuptools/command/easy_install.py", line 693, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/local/lib/python3.5/dist-packages/setuptools/command/easy_install.py", line 719, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/local/lib/python3.5/dist-packages/setuptools/command/easy_install.py", line 904, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/local/lib/python3.5/dist-packages/setuptools/command/easy_install.py", line 1172, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/local/lib/python3.5/dist-packages/setuptools/command/easy_install.py", line 1158, in run_setup
    run_setup(setup_script, args)
  File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/local/lib/python3.5/dist-packages/setuptools/_vendor/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-hkxttng2/MarkupSafe-2.0.0a1/setup.py", line 56, in <module>
    'buildingspy/thirdParty.dymat',
  File "/tmp/easy_install-hkxttng2/MarkupSafe-2.0.0a1/setup.py", line 43, in run_setup
    'simplejson',
  File "/usr/local/lib/python3.5/dist-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.5/distutils/core.py", line 121, in setup
    dist.parse_config_files()
  File "/usr/local/lib/python3.5/dist-packages/setuptools/dist.py", line 690, in parse_config_files
    ignore_option_errors=ignore_option_errors)
  File "/usr/local/lib/python3.5/dist-packages/setuptools/config.py", line 121, in parse_configuration
    meta.parse()
  File "/usr/local/lib/python3.5/dist-packages/setuptools/config.py", line 426, in parse
    section_parser_method(section_options)
  File "/usr/local/lib/python3.5/dist-packages/setuptools/config.py", line 399, in parse_section
    self[name] = value
  File "/usr/local/lib/python3.5/dist-packages/setuptools/config.py", line 184, in __setitem__
    value = parser(value)
  File "/usr/local/lib/python3.5/dist-packages/setuptools/config.py", line 515, in _parse_version
    version = self._parse_attr(value, self.package_dir)
  File "/usr/local/lib/python3.5/dist-packages/setuptools/config.py", line 349, in _parse_attr
    module = import_module(module_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 669, in exec_module
  File "<frozen importlib._bootstrap_external>", line 775, in get_code
  File "<frozen importlib._bootstrap_external>", line 735, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/tmp/easy_install-hkxttng2/MarkupSafe-2.0.0a1/src/markupsafe/__init__.py", line 83
    return f"{self.__class__.__name__}({super().__repr__()})"
                                                            ^
SyntaxError: invalid syntax
```
that's using python 3.5

**Comment by davidism** [comment]
Python 3.5 is not supported. `python_requires` is set appropriately, so whatever pip you're using is too old.

**Comment by Mathadon** [comment]
@davidism okay, thanks for the feedback :)
