### ISSUE TITLE
Python 2.7.x: AttributeError: 'module' object has no attribute '__version__'

### ISSUE THREAD

**Issue by praveenprem** [pallets/markupsafe#119]
Setup tools install **pre-release** version of MarkupSafe for Python 2.7 which cause the following `AttributeError` exception.

```bash
Writing /var/folders/jm/nszzwsfd7tb76tv9b58rx6980000gn/T/easy_install-5rvlNb/MarkupSafe-2.0.0a1/setup.cfg
Running MarkupSafe-2.0.0a1/setup.py -q bdist_egg --dist-dir /var/folders/jm/nszzwsfd7tb76tv9b58rx6980000gn/T/easy_install-5rvlNb/MarkupSafe-2.0.0a1/egg-dist-tmp-lH_2sa
Traceback (most recent call last):
  File "setup.py", line 46, in <module>
.
.
.
.
  File "/Users/praveenpremaratne/.config/system-config/.envs/toolkit/lib/python2.7/site-packages/setuptools/config.py", line 515, in _parse_version
    version = self._parse_attr(value, self.package_dir)
  File "/Users/praveenpremaratne/.config/system-config/.envs/toolkit/lib/python2.7/site-packages/setuptools/config.py", line 350, in _parse_attr
    value = getattr(module, attr_name)
AttributeError: 'module' object has no attribute '__version__'
```

##### MarkupSafe version is NOT defined in the `setup.py`.

_ps: I'm not sure whose end is the error and why Setuptools trying to install a pre-release by default._

> Os: macOS Mojave (10.14.6)
> Python: 2.7.15
> Setuptools: 39.2.0

**Comment by praveenprem** [comment]
By the way, this happens on regardless of which version of Setuptools I use.

**Comment by ThiefMaster** [comment]
are you using `easy_install` by any chance? that's deprecated since a long time...

**Comment by praveenprem** [comment]
No, I'm using `pip`.
```
pip                           20.0.2
```

**Comment by praveenprem** [comment]
I'm using [Virtualenv](https://pypi.org/project/virtualenv/) tho. That does install `easy_install` as well, but I'm not actively using it.

```bash
(test-env) users:():eu-west-1 ➜  (24/04 12:40) BIN/ git:(develop) ✗ ls -la /Users/praveenpremaratne/.config/system-config/.envs/toolkit/bin/
total 544
drwxr-xr-x  67 praveenpremaratne  staff   2144 24 Apr 12:07 .
drwxr-xr-x   6 praveenpremaratne  staff    192 24 Apr 11:58 ..
-rw-r--r--   1 praveenpremaratne  staff   2119 24 Apr 11:59 activate
-rw-r--r--   1 praveenpremaratne  staff   1146 24 Apr 11:59 activate.csh
-rw-r--r--   1 praveenpremaratne  staff   2220 24 Apr 11:59 activate.fish
-rw-r--r--   1 praveenpremaratne  staff   8321 24 Apr 11:59 activate.ps1
-rw-r--r--   1 praveenpremaratne  staff   1143 24 Apr 11:59 activate_this.py
-rwxr-xr-x   1 praveenpremaratne  staff    443 24 Apr 12:07 chardetect
-rwxr-xr-x   1 praveenpremaratne  staff    273 24 Apr 12:07 coverage
-rwxr-xr-x   1 praveenpremaratne  staff    273 24 Apr 12:07 coverage-2.7
-rwxr-xr-x   1 praveenpremaratne  staff    273 24 Apr 12:07 coverage2
-rwxr-xr-x   1 praveenpremaratne  staff    288 24 Apr 12:05 easy_install
-rwxr-xr-x   1 praveenpremaratne  staff    288 24 Apr 12:05 easy_install-2.7
-rwxr-xr-x   1 praveenpremaratne  staff    277 24 Apr 12:07 epylint
-rwxr-xr-x   1 praveenpremaratne  staff    267 24 Apr 12:07 isort
-rwxr-xr-x   1 praveenpremaratne  staff   1733 24 Apr 12:07 jp.py
-rw-r--r--   1 praveenpremaratne  staff   1946 24 Apr 12:07 jp.pyc
-rwxr-xr-x   1 praveenpremaratne  staff    457 24 Apr 12:07 jsonpath.py
-rwxr-xr-x   1 praveenpremaratne  staff    283 24 Apr 11:59 pip
-rwxr-xr-x   1 praveenpremaratne  staff    283 24 Apr 11:59 pip2
-rwxr-xr-x   1 praveenpremaratne  staff    283 24 Apr 11:59 pip2.7
-rwxr-xr-x   1 praveenpremaratne  staff    275 24 Apr 12:07 pylint
-rwxr-xr-x   1 praveenpremaratne  staff    281 24 Apr 12:07 pyreverse
lrwxr-xr-x   1 praveenpremaratne  staff      9 24 Apr 11:58 python -> python2.7
-rwxr-xr-x   1 praveenpremaratne  staff   2378 24 Apr 11:59 python-config
lrwxr-xr-x   1 praveenpremaratne  staff      9 24 Apr 11:58 python2 -> python2.7
-rwxr-xr-x   1 praveenpremaratne  staff  12568 24 Apr 11:58 python2.7
.......
```

**Comment by davidism** [comment]
I can't reproduce this issue. I created a fresh Python 2.7 virtualenv with the given versions of pip and setuptools, and pip installed MarkupSafe 1.1.1 as expected. Even the `--pre` flag still returns 1.1.1 for Python 2.7.

```
$ virtualenv -p 2.7 test
$ . ./test/bin/activate
$ pip install pip==20.0.2 setuptools==39.2.0
$ pip install MarkupSafe
DEPRECATION: Python 2.7 reached the end of its life...
Collecting markupsafe
  Downloading MarkupSafe-1.1.1-cp27-cp27mu-manylinux1_x86_64.whl (24 kB)
Installing collected packages: markupsafe
Successfully installed markupsafe-1.1.1
```

It seems there's something else wrong, perhaps with the env you've created, or the way you're installing the package. This doesn't affect my result, but for some reason you've got the latest pip but a two-year-old version of setuptools. If you can't diagnose the issue further, the best course of action is probably to pin your dependency versions, like `MarkupSafe<2`.

**Comment by praveenprem** [comment]
With `pip` the installation as expected just like yours. But with `Setuptools` it doesn't.

I've put together a repo that can reproduce the issue on my end, could you check if this reproduces the issue on your end as well?

https://github.com/praveenprem/markupsafe-issue-119

_ps: I've used an older version of Setuptools hoping it will force packages to Python2. But even with the latest version, I get the same outcome._

**Comment by davidism** [comment]
You said you're using pip, not setuptools. Setuptools does not understand modern installation metadata, only use pip to install packages.
