### ISSUE TITLE
Fail to install MarkupSafe

### ISSUE THREAD

**Issue by drfwint** [pallets/markupsafe#167]
I am trying to install MarkupSafe and get the following error on 

MacOS 11.0.1 with 
Python 3.9.0 installed via homebrew and
Apple clang version 12.0.0 (clang-1200.0.32.27)

Thanks in advance for the help.

pip install MarkupSafe             
Collecting MarkupSafe
  Using cached MarkupSafe-1.1.1.tar.gz (19 kB)
Building wheels for collected packages: MarkupSafe
  Building wheel for MarkupSafe (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/opt/python@3.9/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/hy/8zks4s092j50pqjncl362krh0000gn/T/pip-install-fpk7mejk/markupsafe_4b9b24980c0b43868aff97ba9d840847/setup.py'"'"'; __file__='"'"'/private/var/folders/hy/8zks4s092j50pqjncl362krh0000gn/T/pip-install-fpk7mejk/markupsafe_4b9b24980c0b43868aff97ba9d840847/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/hy/8zks4s092j50pqjncl362krh0000gn/T/pip-wheel-vbyfos98
       cwd: /private/var/folders/hy/8zks4s092j50pqjncl362krh0000gn/T/pip-install-fpk7mejk/markupsafe_4b9b24980c0b43868aff97ba9d840847/
  Complete output (77 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-11-x86_64-3.9
  creating build/lib.macosx-11-x86_64-3.9/markupsafe
  copying src/markupsafe/_constants.py -> build/lib.macosx-11-x86_64-3.9/markupsafe
  copying src/markupsafe/__init__.py -> build/lib.macosx-11-x86_64-3.9/markupsafe
  copying src/markupsafe/_native.py -> build/lib.macosx-11-x86_64-3.9/markupsafe
  copying src/markupsafe/_compat.py -> build/lib.macosx-11-x86_64-3.9/markupsafe
  running egg_info
  writing src/MarkupSafe.egg-info/PKG-INFO
  writing dependency_links to src/MarkupSafe.egg-info/dependency_links.txt
  writing top-level names to src/MarkupSafe.egg-info/top_level.txt
  reading manifest file 'src/MarkupSafe.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  no previously-included directories found matching 'docs/_build'
  warning: no previously-included files matching '*.py[co]' found anywhere in distribution
  writing manifest file 'src/MarkupSafe.egg-info/SOURCES.txt'
  copying src/markupsafe/_speedups.c -> build/lib.macosx-11-x86_64-3.9/markupsafe
  running build_ext
  building 'markupsafe._speedups' extension
  creating build/temp.macosx-11-x86_64-3.9
  creating build/temp.macosx-11-x86_64-3.9/src
  creating build/temp.macosx-11-x86_64-3.9/src/markupsafe
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk -I/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c src/markupsafe/_speedups.c -o build/temp.macosx-11-x86_64-3.9/src/markupsafe/_speedups.o
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/hy/8zks4s092j50pqjncl362krh0000gn/T/pip-install-fpk7mejk/markupsafe_4b9b24980c0b43868aff97ba9d840847/setup.py", line 105, in <module>
      run_setup(True)
    File "/private/var/folders/hy/8zks4s092j50pqjncl362krh0000gn/T/pip-install-fpk7mejk/markupsafe_4b9b24980c0b43868aff97ba9d840847/setup.py", line 53, in run_setup
      setup(
    File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/private/var/folders/hy/8zks4s092j50pqjncl362krh0000gn/T/pip-install-fpk7mejk/markupsafe_4b9b24980c0b43868aff97ba9d840847/setup.py", line 36, in run
      build_ext.run(self)
    File "/usr/local/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 79, in run
      _build_ext.run(self)
    File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/build_ext.py", line 449, in build_extensions
      self._build_extensions_serial()
    File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/build_ext.py", line 474, in _build_extensions_serial
      self.build_extension(ext)
    File "/private/var/folders/hy/8zks4s092j50pqjncl362krh0000gn/T/pip-install-fpk7mejk/markupsafe_4b9b24980c0b43868aff97ba9d840847/setup.py", line 42, in build_extension
      build_ext.build_extension(self, ext)
    File "/usr/local/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
      _build_ext.build_extension(self, ext)
    File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/build_ext.py", line 529, in build_extension
      objects = self.compiler.compile(sources,
    File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/ccompiler.py", line 574, in compile
      self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
    File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/unixccompiler.py", line 117, in _compile
      self.spawn(compiler_so + cc_args + [src, '-o', obj] +
    File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/ccompiler.py", line 910, in spawn
      spawn(cmd, dry_run=self.dry_run)
    File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/spawn.py", line 66, in spawn
      if _cfg_target_split > [int(x) for x in cur_target.split('.')]:
  AttributeError: 'int' object has no attribute 'split'
  ----------------------------------------
  ERROR: Failed building wheel for MarkupSafe
  Running setup.py clean for MarkupSafe
Failed to build MarkupSafe
Installing collected packages: MarkupSafe
    Running setup.py install for MarkupSafe ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python@3.9/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/hy/8zks4s092j50pqjncl362krh0000gn/T/pip-install-fpk7mejk/markupsafe_4b9b24980c0b43868aff97ba9d840847/setup.py'"'"'; __file__='"'"'/private/var/folders/hy/8zks4s092j50pqjncl362krh0000gn/T/pip-install-fpk7mejk/markupsafe_4b9b24980c0b43868aff97ba9d840847/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/hy/8zks4s092j50pqjncl362krh0000gn/T/pip-record-om6y9hd_/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/MarkupSafe
         cwd: /private/var/folders/hy/8zks4s092j50pqjncl362krh0000gn/T/pip-install-fpk7mejk/markupsafe_4b9b24980c0b43868aff97ba9d840847/
    Complete output (79 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-11-x86_64-3.9
    creating build/lib.macosx-11-x86_64-3.9/markupsafe
    copying src/markupsafe/_constants.py -> build/lib.macosx-11-x86_64-3.9/markupsafe
    copying src/markupsafe/__init__.py -> build/lib.macosx-11-x86_64-3.9/markupsafe
    copying src/markupsafe/_native.py -> build/lib.macosx-11-x86_64-3.9/markupsafe
    copying src/markupsafe/_compat.py -> build/lib.macosx-11-x86_64-3.9/markupsafe
    running egg_info
    writing src/MarkupSafe.egg-info/PKG-INFO
    writing dependency_links to src/MarkupSafe.egg-info/dependency_links.txt
    writing top-level names to src/MarkupSafe.egg-info/top_level.txt
    reading manifest file 'src/MarkupSafe.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    no previously-included directories found matching 'docs/_build'
    warning: no previously-included files matching '*.py[co]' found anywhere in distribution
    writing manifest file 'src/MarkupSafe.egg-info/SOURCES.txt'
    copying src/markupsafe/_speedups.c -> build/lib.macosx-11-x86_64-3.9/markupsafe
    running build_ext
    building 'markupsafe._speedups' extension
    creating build/temp.macosx-11-x86_64-3.9
    creating build/temp.macosx-11-x86_64-3.9/src
    creating build/temp.macosx-11-x86_64-3.9/src/markupsafe
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk -I/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c src/markupsafe/_speedups.c -o build/temp.macosx-11-x86_64-3.9/src/markupsafe/_speedups.o
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/hy/8zks4s092j50pqjncl362krh0000gn/T/pip-install-fpk7mejk/markupsafe_4b9b24980c0b43868aff97ba9d840847/setup.py", line 105, in <module>
        run_setup(True)
      File "/private/var/folders/hy/8zks4s092j50pqjncl362krh0000gn/T/pip-install-fpk7mejk/markupsafe_4b9b24980c0b43868aff97ba9d840847/setup.py", line 53, in run_setup
        setup(
      File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.9/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/install.py", line 546, in run
        self.run_command('build')
      File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/hy/8zks4s092j50pqjncl362krh0000gn/T/pip-install-fpk7mejk/markupsafe_4b9b24980c0b43868aff97ba9d840847/setup.py", line 36, in run
        build_ext.run(self)
      File "/usr/local/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/private/var/folders/hy/8zks4s092j50pqjncl362krh0000gn/T/pip-install-fpk7mejk/markupsafe_4b9b24980c0b43868aff97ba9d840847/setup.py", line 42, in build_extension
        build_ext.build_extension(self, ext)
      File "/usr/local/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
        _build_ext.build_extension(self, ext)
      File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/build_ext.py", line 529, in build_extension
        objects = self.compiler.compile(sources,
      File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/ccompiler.py", line 574, in compile
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
      File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/unixccompiler.py", line 117, in _compile
        self.spawn(compiler_so + cc_args + [src, '-o', obj] +
      File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/ccompiler.py", line 910, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/spawn.py", line 66, in spawn
        if _cfg_target_split > [int(x) for x in cur_target.split('.')]:
    AttributeError: 'int' object has no attribute 'split'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/opt/python@3.9/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/hy/8zks4s092j50pqjncl362krh0000gn/T/pip-install-fpk7mejk/markupsafe_4b9b24980c0b43868aff97ba9d840847/setup.py'"'"'; __file__='"'"'/private/var/folders/hy/8zks4s092j50pqjncl362krh0000gn/T/pip-install-fpk7mejk/markupsafe_4b9b24980c0b43868aff97ba9d840847/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/hy/8zks4s092j50pqjncl362krh0000gn/T/pip-record-om6y9hd_/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/MarkupSafe Check the logs for full command output.

**Comment by greyli** [comment]
This seems a bug of Homebrew (https://github.com/Homebrew/homebrew-core/issues/66096).

**Comment by drfwint** [comment]
Thanks for the hint!
