### ISSUE TITLE
MarkupSafe cannot import name 'Feature'

### ISSUE THREAD

**Issue by vancityhuddy** [pallets/markupsafe#187]
MarkupSafe 1.0 is a dependency of our project, and it appears to have been broken sometime in the past few days, as this was all over my AWS elastic beanstalk error logs:
```
Collecting MarkupSafe==1.0
    Using cached MarkupSafe-1.0.tar.gz (14 kB)
      ERROR: Command errored out with exit status 1:
       command: /opt/python/run/venv/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-6poufw_y/markupsafe_72b1c8a6abef417dae8a154089bd0ea5/setup.py'"'"'; __file__='"'"'/tmp/pip-install-6poufw_y/markupsafe_72b1c8a6abef417dae8a154089bd0ea5/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-odjdbh8q
           cwd: /tmp/pip-install-6poufw_y/markupsafe_72b1c8a6abef417dae8a154089bd0ea5/
      Complete output (5 lines):
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/tmp/pip-install-6poufw_y/markupsafe_72b1c8a6abef417dae8a154089bd0ea5/setup.py", line 6, in <module>          from setuptools import setup, Extension, Feature
      ImportError: cannot import name 'Feature'
      ----------------------------------------
  WARNING: Discarding https://files.pythonhosted.org/packages/4d/de/32d741db316d8fdb7680822dd37001ef7a448255de9699ab4bfcbdf4172b/MarkupSafe-1.0.tar.gz#sha256=(from https://pypi.org/simple/markupsafe/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.  ERROR: Could not find a version that satisfies the requirement MarkupSafe==1.0
  ERROR: No matching distribution found for MarkupSafe==1.0
```

The solution was to upgrade the lib to 1.1.1.

What happened to cause this issue?

**Comment by davidism** [comment]
The 1.0 releases on PyPI have not changed. Sounds like you finally updated from a very old version of setuptools. #116, #57, #24, #23 Upgrading to 1.1 is the correct solution, and should be done anyway. Be sure to pin all your dependencies, including setuptools and pip, in order to control your deploy environment.

**Comment by vancityhuddy** [comment]
This must have been a change at the AWS level then. Thank you for the assistance!
