### ISSUE TITLE
Installing MarkupSafe 2.0.0 on Ubuntu 18.04 fails

### ISSUE THREAD

**Issue by sjkummer** [pallets/markupsafe#214]
How to replicate:
Run `pip3 install -U MarkupSafe` on Ubuntu 18.04 

Environment:

- Python version: 3.6.9
- MarkupSafe version: 2.0.0
- OS: Ubuntu 18.04 (aarch64)

Log:
```
pip3 install -U MarkupSafe
Collecting MarkupSafe
  Using cached https://files.pythonhosted.org/packages/67/6a/5b3ed5c122e20c33d2562df06faf895a6b91b0a6b96a4626440ffe1d5c8e/MarkupSafe-2.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-628gt7q8/MarkupSafe/setup.py", line 61, in <module>
        run_setup(True)
      File "/tmp/pip-build-628gt7q8/MarkupSafe/setup.py", line 44, in run_setup
        ext_modules=ext_modules if with_binary else [],
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 121, in setup
        dist.parse_config_files()
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 494, in parse_config_files
        ignore_option_errors=ignore_option_errors)
      File "/usr/lib/python3/dist-packages/setuptools/config.py", line 106, in parse_configuration
        meta.parse()
      File "/usr/lib/python3/dist-packages/setuptools/config.py", line 382, in parse
        section_parser_method(section_options)
      File "/usr/lib/python3/dist-packages/setuptools/config.py", line 355, in parse_section
        self[name] = value
      File "/usr/lib/python3/dist-packages/setuptools/config.py", line 173, in __setitem__
        value = parser(value)
      File "/usr/lib/python3/dist-packages/setuptools/config.py", line 430, in _parse_version
        version = self._parse_attr(value)
      File "/usr/lib/python3/dist-packages/setuptools/config.py", line 305, in _parse_attr
        module = import_module(module_name)
      File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'markupsafe'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-628gt7q8/MarkupSafe/
```

**Comment by davidism** [comment]
You'll need to upgrade pip. It looks like you might be using the system python. You should use a virtualenv to pip install packages separate from the system. Use apt to install system packages.
