### ISSUE TITLE
Can't Install Markup Space

### ISSUE THREAD

**Issue by jayantkageri** [pallets/markupsafe#226]
Hi, I was Installing Markup Space and I got this error
```
         Downloading MarkupSafe-1.0.tar.gz (14 kB)
           ERROR: Command errored out with exit status 1:
            command: /app/.heroku/python/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-j8bn7t7f/markupsafe/setup.py'"'"'; __file__='"'"'/tmp/pip-install-j8bn7t7f/markupsafe/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-n2hxrpe9
                cwd: /tmp/pip-install-j8bn7t7f/markupsafe/
           Complete output (5 lines):
           Traceback (most recent call last):
             File "<string>", line 1, in <module>
             File "/tmp/pip-install-j8bn7t7f/markupsafe/setup.py", line 6, in <module>
               from setuptools import setup, Extension, Feature
           ImportError: cannot import name 'Feature'
           ----------------------------------------
```

- Python version: 3.6.13
- MarkupSafe version: 1.0

**Comment by greyli** [comment]
setuptools removed the `Feature` class in version 46.0.0, while Markupsafe uses this class in version 1.0. there are two methods to fix this:

1. Back to the old version of setuptools:

```
pip install setuptools==39.2.0
```

2. Upgrade Marupsafe to the latest version:

```
pip install -U markupsafe
```
