### ISSUE TITLE
ImportError: cannot import name 'soft_unicode' from 'markupsafe' 

### ISSUE THREAD

**Issue by nachiketrss** [pallets/markupsafe#282]
requirements.txt:
flask~=1.1.2
pandas~=1.2.2
Werkzeug~=1.0.1
numpy~=1.20.1
twilio~=7.2.0
waitress~=2.0.0
pyjwt~=2.3.0
cryptography~=36.0.1

python -m venv venv
venv\scripts\activate
pip install -r requirements.txt

python app.py

Error:
(venv) D:\SonicApi>python app.py
Traceback (most recent call last):
  File "D:\SonicApi\app.py", line 8, in <module>
    from flask import Flask, request, abort, jsonify
  File "D:\SonicApi\venv\lib\site-packages\flask\__init__.py", line 14, in <module>
    from jinja2 import escape
  File "D:\SonicApi\venv\lib\site-packages\jinja2\__init__.py", line 12, in <module>
    from .environment import Environment
  File "D:\SonicApi\venv\lib\site-packages\jinja2\environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "D:\SonicApi\venv\lib\site-packages\jinja2\defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "D:\SonicApi\venv\lib\site-packages\jinja2\filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (D:\SonicApi\venv\lib\site-packages\markupsafe\__init__.py)

- Python version: Python 3.9.10
- MarkupSafe version: MarkupSafe 2.1.0

**Comment by davidism** [comment]
Duplicate of #1585

**Comment by qeternity** [comment]
> You are using an unsupported version of Jinja, please update to the latest version. Additionally, please read https://hynek.me/articles/semver-will-not-save-you/, then use a tool like [pip-tools](https://pypi.org/project/pip-tools/) to pin your dependencies and control when you get updates. Be sure to run your tests with deprecation warnings treated as errors so that you get notified of these types of changes early.

Very puzzling reply. The article you link about semver makes the argument that people implement semver poorly, which is exactly what we're witnessing here. Unsupported version or not, this is sloppy.

**Comment by hiaselhans** [comment]
i think it would really help to leave at least one of these issues open...

if not for others then for you, to save some work closing new issues.

:peace_symbol:

**Comment by ThiefMaster** [comment]
It is pinned... I'm not sure whether it being open would help in giving it visibility.

**Comment by hiaselhans** [comment]
oh, sorry i didn't see that!

so then, just for me and i found it already. Sorry for the noise

**Comment by moorepants** [comment]
> use a tool like [pip-tools](https://pypi.org/project/pip-tools/) to pin your dependencies and control when you get updates

This is an unreasonable expectation. If markupsafe is a library that is fairly deep in the dependency stack of many many projects, it is important to maintain API stability and if the API has to break, then a deprecation cycle is needed, to warn upstream packages before the API is changed in a non-breaking way. I don't know if the API change is here or in Jinja, but just closing this issue and expecting everyone to pin all dependencies only works if everyone is working on non-library codes at the top of the dependency stack.

**Comment by ThiefMaster** [comment]
It was marked as deprecated since the last major release, so people with deprecation warnings enabled (ideally configured as errors in CI pipelines etc) would have seen that warning...

**Comment by qeternity** [comment]
Deprecation warnings or not, all of this misses the core issue: a breaking change was introduced in a minor version. Plenty of people had their deps properly pinned, allowing for minor and patch upgrades. Whether or not semver is a silver bullet, the entire point of it is to avoid issues exactly like this.

**Comment by moorepants** [comment]
Deprecation warnings should be loud, IMHO.
