### ISSUE TITLE
problem in github action sam build

### ISSUE THREAD

**Issue by nirob-appsbee** [pallets/markupsafe#287]
-->
In MarkupSafe version:2.1.0 removed the "soft_unicode" and for this sam build not possible in github aciton. the error is:
>>>>>
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/home/runner/work/_temp/setup-sam-DDWeLr/.venv/lib/python3.9/site-packages/markupsafe/__init__.py)

>>>

there is a code example of github action error example:

================

Run sam build

	SAM CLI now collects telemetry to better understand customer needs.

	You can OPT OUT and disable telemetry collection by setting the
	environment variable SAM_CLI_TELEMETRY=0 in your shell.
	Thanks for your help!

	Learn More: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-telemetry.html

Traceback (most recent call last):
  File "/home/runner/work/_temp/setup-sam-DDWeLr/bin/sam", line 8, in <module>
    sys.exit(cli())
  File "/home/runner/work/_temp/setup-sam-DDWeLr/.venv/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/runner/work/_temp/setup-sam-DDWeLr/.venv/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/runner/work/_temp/setup-sam-DDWeLr/.venv/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/runner/work/_temp/setup-sam-DDWeLr/.venv/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/runner/work/_temp/setup-sam-DDWeLr/.venv/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/runner/work/_temp/setup-sam-DDWeLr/.venv/lib/python3.9/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/runner/work/_temp/setup-sam-DDWeLr/.venv/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/runner/work/_temp/setup-sam-DDWeLr/.venv/lib/python3.9/site-packages/samcli/lib/telemetry/metric.py", line 166, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "/home/runner/work/_temp/setup-sam-DDWeLr/.venv/lib/python3.9/site-packages/samcli/lib/telemetry/metric.py", line 124, in wrapped
    return_value = func(*args, **kwargs)
  File "/home/runner/work/_temp/setup-sam-DDWeLr/.venv/lib/python3.9/site-packages/samcli/lib/utils/version_checker.py", line 41, in wrapped
    actual_result = func(*args, **kwargs)
  File "/home/runner/work/_temp/setup-sam-DDWeLr/.venv/lib/python3.9/site-packages/samcli/cli/main.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/home/runner/work/_temp/setup-sam-DDWeLr/.venv/lib/python3.9/site-packages/samcli/commands/build/command.py", line 174, in cli
    do_cli(
  File "/home/runner/work/_temp/setup-sam-DDWeLr/.venv/lib/python3.9/site-packages/samcli/commands/build/command.py", line 220, in do_cli
    from samcli.commands.build.build_context import BuildContext
  File "/home/runner/work/_temp/setup-sam-DDWeLr/.venv/lib/python3.9/site-packages/samcli/commands/build/build_context.py", line 13, in <module>
    from samcli.lib.providers.sam_api_provider import SamApiProvider
  File "/home/runner/work/_temp/setup-sam-DDWeLr/.venv/lib/python3.9/site-packages/samcli/lib/providers/sam_api_provider.py", line 6, in <module>
    from samcli.lib.providers.api_collector import ApiCollector
  File "/home/runner/work/_temp/setup-sam-DDWeLr/.venv/lib/python3.9/site-packages/samcli/lib/providers/api_collector.py", line 10, in <module>
    from samcli.local.apigw.local_apigw_service import Route
  File "/home/runner/work/_temp/setup-sam-DDWeLr/.venv/lib/python3.9/site-packages/samcli/local/apigw/local_apigw_service.py", line [11](https://github.com/appsbee/No-Soliciting-Sales-App-Backend/runs/5246939887?check_suite_focus=true#step:9:11), in <module>
    from flask import Flask, request
  File "/home/runner/work/_temp/setup-sam-DDWeLr/.venv/lib/python3.9/site-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
  File "/home/runner/work/_temp/setup-sam-DDWeLr/.venv/lib/python3.9/site-packages/jinja2/__init__.py", line [12](https://github.com/appsbee/No-Soliciting-Sales-App-Backend/runs/5246939887?check_suite_focus=true#step:9:12), in <module>
    from .environment import Environment
  File "/home/runner/work/_temp/setup-sam-DDWeLr/.venv/lib/python3.9/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/home/runner/work/_temp/setup-sam-DDWeLr/.venv/lib/python3.9/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/home/runner/work/_temp/setup-sam-DDWeLr/.venv/lib/python3.9/site-packages/jinja2/filters.py", line [13](https://github.com/appsbee/No-Soliciting-Sales-App-Backend/runs/5246939887?check_suite_focus=true#step:9:13), in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/home/runner/work/_temp/setup-sam-DDWeLr/.venv/lib/python3.9/site-packages/markupsafe/__init__.py)
Error: Process completed with exit code 1.

=============================================

Environment:

- Python version:3.9
- MarkupSafe version:2.1.0

**Comment by davidism** [comment]
You are using an unsupported version of Jinja, please update to the latest version. Additionally, please read https://hynek.me/articles/semver-will-not-save-you/, then use a tool like [pip-tools](https://pypi.org/project/pip-tools/) to pin your dependencies and control when you get updates. Be sure to run your tests with deprecation warnings treated as errors so that you get notified of these types of changes early.

**Comment by nirob-appsbee** [comment]
if i use Jinja2==3.0.3 then i am facing this issue 
============
cannot import name 'json' from 'itsdangerous' (/var/task/itsdangerous/__init__.

============
