### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by eljeffeg** [pallets/markupsafe#296]
Python 2.7
```
Downloading https://files.pythonhosted.org/packages/1d/97/2288fe498044284f39ab8950703e88abbac2abbdf65524d576157af70556/MarkupSafe-2.1.1.tar.gz
#9 3.516     Complete output from command python setup.py egg_info:
#9 3.516     Traceback (most recent call last):
#9 3.516       File "<string>", line 1, in <module>
#9 3.516       File "/tmp/pip-build-s5GRSz/MarkupSafe/setup.py", line 26
#9 3.516         raise BuildFailed() from e
#9 3.516                                ^
#9 3.516     SyntaxError: invalid syntax
#9 3.516     
#9 3.516     ----------------------------------------
#9 3.539 Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-s5GRSz/MarkupSafe/
```
From a docker build, fails installing flask
```
FROM  ubuntu:16.04

RUN apt-get update -y && apt-get install -y libpangocairo-1.0-0 libx11-xcb1 libxcomposite1 libxcursor1 libxdamage1 libxi6 libxtst6 libnss3 libcups2 libxss1 libxrandr2 libgconf2-4 libasound2 libatk1.0-0 libgtk-3-0 
RUN apt-get install -y curl supervisor python2.7 python-pip && (curl -sL https://deb.nodesource.com/setup_8.x | bash -) 
RUN apt-get install -y nodejs 
RUN npm i puppeteer 
RUN pip install flask requests gunicorn 
```

**Comment by ThiefMaster** [comment]
Do you really expect a recent version of pretty much any Python library to work on an EOL Python version? ;)

**Comment by eljeffeg** [comment]
idk, could be a really easy fix that was unintended.  Could be broken on Py3 too.. didn't test.  I'm just trying to run someone else's docker and getting stuck.

**Comment by ThiefMaster** [comment]
I guess they use an incredibly ancient pip version which does not take Python version requirements into account, and did not pin dependency versions either. So you probably won't be able to run that dockerfile without making changes (ideally using a recent Python 3)
