### ISSUE TITLE
Unable to upgrade Markupsafe due to dependency with Werkzeug and Jinja2, best possible combination only possible with earlier versions

### ISSUE THREAD

**Issue by sajin-sadanandan-db** [pallets/markupsafe#354]
Environment:

- Python version: clearlinux/python:3:10
Jinja2==3.0.3
Werkzeug==2.0.3
MarkupSafe==2.0.1

**Comment by ThiefMaster** [comment]
You may need to upgrade werkzeug/jinja as well.

**Comment by sajin-sadanandan-db** [comment]
Hi ThiefMaster, I already tried that, but there was always conflicts apart from the combination i mentioned, could not get better upgraded version for the combination.

**Comment by ThiefMaster** [comment]
you may want to use a tool like `pip-compile` to which you feed your list of dependencies (without pinning) and then list it generates a requirements.txt (with pinning) which satisfies all constraints.

**Comment by davidism** [comment]
You are using an unsupported version of the libraries, please update to the latest versions if possible.

When writing an application, you _must_ use a tool like [pip-tools](https://pypi.org/project/pip-tools/) to pin your application's full dependency tree. This gives you reproducible deployments, allowing you to control when you get updates. Be sure to run your tests with deprecation warnings treated as errors so that you get notified of those types of changes early.

Please review any of the following for more information:

* https://hynek.me/articles/semver-will-not-save-you/
* https://www.youtube.com/watch?v=WSVFw-3ssXM&t
* https://snarky.ca/why-i-dont-like-semver/
* https://caremad.io/posts/2016/02/versioning-software/
* https://bernat.tech/posts/version-numbers/
* https://iscinumpy.dev/post/bound-version-constraints/

**Comment by davidism** [comment]
You are using an unsupported version of the libraries, please update to the latest versions if possible.

When writing an application, you _must_ use a tool like [pip-tools](https://pypi.org/project/pip-tools/) to pin your application's full dependency tree. This gives you reproducible deployments, allowing you to control when you get updates. Be sure to run your tests with deprecation warnings treated as errors so that you get notified of those types of changes early.

**Comment by sajin-sadanandan-db** [comment]
davidism, i tried to upgrade versions as per instruction from xray tool, 
Werkzeug==2.2.3
MarkupSafe==2.1.1
Jinja2==3.0.3
deployment was success, but the pods failed with below message:
Traceback (most recent call last): File "/opt/env/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker worker.init_process() File "/opt/env/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process self.load_wsgi() File "/opt/env/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi self.wsgi = self.app.wsgi() File "/opt/env/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi self.callable = self.load() File "/opt/env/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load return self.load_wsgiapp() File "/opt/env/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp return util.import_app(self.app_uri) File "/opt/env/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app mod = importlib.import_module(module) File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "<frozen importlib._bootstrap>", line 1050, in _gcd_import File "<frozen importlib._bootstrap>", line 1027, in _find_and_load File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 688, in _load_unlocked File "<frozen importlib._bootstrap_external>", line 883, in exec_module File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed File "/py/wsgi.py", line 2, in <module> from app import app File "/py/app.py", line 9, in <module> from flask import Flask, render_template, request, url_for, \ File "/opt/env/lib/python3.10/site-packages/flask/__init__.py", line 21, in <module> from .app import Flask File "/opt/env/lib/python3.10/site-packages/flask/app.py", line 32, in <module> from werkzeug.wrappers import BaseResponse ImportError: cannot import name 'BaseResponse' from 'werkzeug.wrappers' (/opt/env/lib/python3.10/site-packages/werkzeug/wrappers/__init__.py)

Similar issue is found in https://github.com/mjmeijer/donald_2021/issues/4

**Comment by ThiefMaster** [comment]
can you please post your tracebacks etc with proper formatting? it's a mess to read...

**Comment by davidism** [comment]
Sorry, we can't help you here. You'll need to debug your project yourself.
