### ISSUE TITLE
pin markupsafe==2.0.1

### ISSUE THREAD

**Issue by fraser-langton** [pallets/markupsafe#371]
soft_unicode not in latest markupsafe

```
> mrgenerator-cli --help
Traceback (most recent call last):
  File "C:\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Path\to\mrgenerator-cli.exe\__main__.py", line 4, in <module>
  File "C:\Path\to\mrgenerator\run.py", line 3, in <module>
    from mrgenerator.generator import Generator
  File "C:\Path\to\mrgenerator\generator.py", line 1, in <module>
    from jinja2 import Environment, FileSystemLoader
  File "C:\Path\to\jinja2\__init__.py", line 12, in <module>
    from .environment import Environment
  File "C:\Path\to\jinja2\environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "C:\Path\to\jinja2\defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "C:\Path\to\jinja2\filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (C:\Path\to\markupsafe\__init__.py)
```

**Comment by ThiefMaster** [comment]
Update jinja.
