### ISSUE TITLE
`TypeError: 'NoneType' object is not iterable` when installing MarkupSafe v0.23 on MSYS2

### ISSUE THREAD

**Issue by edmorley** [pallets/markupsafe#46]
I'm using MSYS2 (fork of Gygwin), Python 2.7.10, pip 7.1.2, msys2's gcc 4.9.2, on Windows 8.1 x64.

```bash
$ pip install sphinx
Collecting sphinx
  Using cached Sphinx-1.3.1-py2.py3-none-any.whl
Collecting sphinx-rtd-theme<0.2,>=0.1 (from sphinx)
  Using cached sphinx_rtd_theme-0.1.9-py2-none-any.whl
Collecting snowballstemmer>=1.1 (from sphinx)
Collecting six>=1.4 (from sphinx)
  Using cached six-1.9.0-py2.py3-none-any.whl
Collecting Pygments>=2.0 (from sphinx)
  Using cached Pygments-2.0.2-py2-none-any.whl
Collecting docutils>=0.11 (from sphinx)
Collecting babel>=1.3 (from sphinx)
Collecting Jinja2>=2.3 (from sphinx)
  Using cached Jinja2-2.8-py2.py3-none-any.whl
Collecting alabaster<0.8,>=0.7 (from sphinx)
  Using cached alabaster-0.7.6-py2-none-any.whl
Collecting pytz>=0a (from babel>=1.3->sphinx)
  Using cached pytz-2015.6-py2.py3-none-any.whl
Collecting MarkupSafe (from Jinja2>=2.3->sphinx)
  Using cached MarkupSafe-0.23.tar.gz
Building wheels for collected packages: MarkupSafe
  Running setup.py bdist_wheel for MarkupSafe
  Complete output from command /home/Ed/.virtualenvs/bugsy2/bin/python -c "import setuptools;__file__='/tmp/pip-build-wb1swt/MarkupSafe/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmp1FkDLRpip-wheel-:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.mingw32_nt-6.3-2.3.0(0.290
  creating build/lib.mingw32_nt-6.3-2.3.0(0.290/5
  creating build/lib.mingw32_nt-6.3-2.3.0(0.290/5/3)-x86_64-2.7
  creating build/lib.mingw32_nt-6.3-2.3.0(0.290/5/3)-x86_64-2.7/markupsafe
  copying markupsafe/tests.py -> build/lib.mingw32_nt-6.3-2.3.0(0.290/5/3)-x86_64-2.7/markupsafe
  copying markupsafe/_compat.py -> build/lib.mingw32_nt-6.3-2.3.0(0.290/5/3)-x86_64-2.7/markupsafe
  copying markupsafe/_constants.py -> build/lib.mingw32_nt-6.3-2.3.0(0.290/5/3)-x86_64-2.7/markupsafe
  copying markupsafe/_native.py -> build/lib.mingw32_nt-6.3-2.3.0(0.290/5/3)-x86_64-2.7/markupsafe
  copying markupsafe/__init__.py -> build/lib.mingw32_nt-6.3-2.3.0(0.290/5/3)-x86_64-2.7/markupsafe
  running egg_info
  writing MarkupSafe.egg-info/PKG-INFO
  writing top-level names to MarkupSafe.egg-info/top_level.txt
  writing dependency_links to MarkupSafe.egg-info/dependency_links.txt
  warning: manifest_maker: standard file '-c' not found

  reading manifest file 'MarkupSafe.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'MarkupSafe.egg-info/SOURCES.txt'
  copying markupsafe/_speedups.c -> build/lib.mingw32_nt-6.3-2.3.0(0.290/5/3)-x86_64-2.7/markupsafe
  running build_ext
  building 'markupsafe._speedups' extension
  creating build/temp.mingw32_nt-6.3-2.3.0(0.290
  creating build/temp.mingw32_nt-6.3-2.3.0(0.290/5
  creating build/temp.mingw32_nt-6.3-2.3.0(0.290/5/3)-x86_64-2.7
  creating build/temp.mingw32_nt-6.3-2.3.0(0.290/5/3)-x86_64-2.7/markupsafe
  gcc -mdll -O -Wall -I/usr/include/python2.7 -c markupsafe/_speedups.c -o build/temp.mingw32_nt-6.3-2.3.0(0.290/5/3)-x86_64-2.7/markupsafe/_speedups.o
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-wb1swt/MarkupSafe/setup.py", line 120, in <module>
      try_building_extension()
    File "/tmp/pip-build-wb1swt/MarkupSafe/setup.py", line 99, in try_building_extension
      run_setup(True)
    File "/tmp/pip-build-wb1swt/MarkupSafe/setup.py", line 93, in run_setup
      ext_modules=ext_modules,
    File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/home/Ed/.virtualenvs/bugsy2/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 175, in run
      self.run_command('build')
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/lib/python2.7/distutils/command/build.py", line 127, in run
      self.run_command(cmd_name)
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-wb1swt/MarkupSafe/setup.py", line 41, in run
      build_ext.run(self)
    File "/usr/lib/python2.7/distutils/command/build_ext.py", line 337, in run
      self.build_extensions()
    File "/usr/lib/python2.7/distutils/command/build_ext.py", line 446, in build_extensions
      self.build_extension(ext)
    File "/tmp/pip-build-wb1swt/MarkupSafe/setup.py", line 47, in build_extension
      build_ext.build_extension(self, ext)
    File "/usr/lib/python2.7/distutils/command/build_ext.py", line 528, in build_extension
      target_lang=language)
    File "/usr/lib/python2.7/distutils/ccompiler.py", line 691, in link_shared_object
      extra_preargs, extra_postargs, build_temp, target_lang)
    File "/usr/lib/python2.7/distutils/cygwinccompiler.py", line 189, in link
      libraries.extend(self.dll_libraries)
  TypeError: 'NoneType' object is not iterable

  ----------------------------------------
  Failed building wheel for MarkupSafe
Failed to build MarkupSafe
Installing collected packages: sphinx-rtd-theme, snowballstemmer, six, Pygments, docutils, pytz, babel, MarkupSafe, Jinja2, alabaster, sphinx
  Running setup.py install for MarkupSafe
    Complete output from command /home/Ed/.virtualenvs/bugsy2/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-wb1swt/MarkupSafe/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-wPGgLg-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/Ed/.virtualenvs/bugsy2/include/site/python2.7/MarkupSafe:
    running install
    running build
    running build_py
    running egg_info
    writing MarkupSafe.egg-info/PKG-INFO
    writing top-level names to MarkupSafe.egg-info/top_level.txt
    writing dependency_links to MarkupSafe.egg-info/dependency_links.txt
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'MarkupSafe.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'MarkupSafe.egg-info/SOURCES.txt'
    running build_ext
    building 'markupsafe._speedups' extension
    gcc -mdll -O -Wall -I/usr/include/python2.7 -c markupsafe/_speedups.c -o build/temp.mingw32_nt-6.3-2.3.0(0.290/5/3)-x86_64-2.7/markupsafe/_speedups.o
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-wb1swt/MarkupSafe/setup.py", line 120, in <module>
        try_building_extension()
      File "/tmp/pip-build-wb1swt/MarkupSafe/setup.py", line 99, in try_building_extension
        run_setup(True)
      File "/tmp/pip-build-wb1swt/MarkupSafe/setup.py", line 93, in run_setup
        ext_modules=ext_modules,
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/Ed/.virtualenvs/bugsy2/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python2.7/distutils/command/install.py", line 563, in run
        self.run_command('build')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/distutils/command/build.py", line 127, in run
        self.run_command(cmd_name)
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-wb1swt/MarkupSafe/setup.py", line 41, in run
        build_ext.run(self)
      File "/usr/lib/python2.7/distutils/command/build_ext.py", line 337, in run
        self.build_extensions()
      File "/usr/lib/python2.7/distutils/command/build_ext.py", line 446, in build_extensions
        self.build_extension(ext)
      File "/tmp/pip-build-wb1swt/MarkupSafe/setup.py", line 47, in build_extension
        build_ext.build_extension(self, ext)
      File "/usr/lib/python2.7/distutils/command/build_ext.py", line 528, in build_extension
        target_lang=language)
      File "/usr/lib/python2.7/distutils/ccompiler.py", line 691, in link_shared_object
        extra_preargs, extra_postargs, build_temp, target_lang)
      File "/usr/lib/python2.7/distutils/cygwinccompiler.py", line 189, in link
        libraries.extend(self.dll_libraries)
    TypeError: 'NoneType' object is not iterable

    ----------------------------------------
Command "/home/Ed/.virtualenvs/bugsy2/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-wb1swt/MarkupSafe/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-wPGgLg-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/Ed/.virtualenvs/bugsy2/include/site/python2.7/MarkupSafe" failed with error code 1 in /tmp/pip-build-wb1swt/MarkupSafe
```

**Comment by davidism** [comment]
This is an issue with Python and distutils, which don't support msys2 builds as far as I can tell, not with MarkupSafe.  There is nothing we can do here to fix this.
