### ISSUE TITLE
Error while installing in Windows 7

### ISSUE THREAD

**Issue by jperezr21** [pallets/markupsafe#47]
I'm getting this error while installing the package in Windows 7. Maybe has something to do with my windows username, which has a non-ASCII character.
```
>> python setup.py install
running install
running bdist_egg
running egg_info
writing MarkupSafe.egg-info\PKG-INFO
writing top-level names to MarkupSafe.egg-info\top_level.txt
writing dependency_links to MarkupSafe.egg-info\dependency_links.txt
reading manifest file 'MarkupSafe.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'MarkupSafe.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_py
running build_ext
building 'markupsafe._speedups' extension
Traceback (most recent call last):
  File "setup.py", line 120, in <module>
    try_building_extension()
  File "setup.py", line 99, in try_building_extension
    run_setup(True)
  File "setup.py", line 93, in run_setup
    ext_modules=ext_modules,
  File "C:\python27\lib\distutils\core.py", line 151, in setup
    dist.run_commands()
  File "C:\python27\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "C:\python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "build\bdist.win32\egg\setuptools\command\install.py", line 67, in run
  File "build\bdist.win32\egg\setuptools\command\install.py", line 109, in do_egg_install
  File "C:\python27\lib\distutils\cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "C:\python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "build\bdist.win32\egg\setuptools\command\bdist_egg.py", line 160, in run
  File "build\bdist.win32\egg\setuptools\command\bdist_egg.py", line 146, in call_command
  File "C:\python27\lib\distutils\cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "C:\python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "build\bdist.win32\egg\setuptools\command\install_lib.py", line 10, in run
  File "C:\python27\lib\distutils\command\install_lib.py", line 111, in build
    self.run_command('build_ext')
  File "C:\python27\lib\distutils\cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "C:\python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 41, in run
    build_ext.run(self)
  File "C:\python27\lib\distutils\command\build_ext.py", line 337, in run
    self.build_extensions()
  File "C:\python27\lib\distutils\command\build_ext.py", line 446, in build_extensions
    self.build_extension(ext)
  File "setup.py", line 47, in build_extension
    build_ext.build_extension(self, ext)
  File "C:\python27\lib\distutils\command\build_ext.py", line 496, in build_extension
    depends=ext.depends)
  File "C:\python27\lib\distutils\msvc9compiler.py", line 473, in compile
    self.initialize()
  File "C:\python27\lib\distutils\msvc9compiler.py", line 383, in initialize
    vc_env = query_vcvarsall(VERSION, plat_spec)
  File "build\bdist.win32\egg\setuptools\msvc9_support.py", line 52, in query_vcvarsall
  File "C:\python27\lib\distutils\msvc9compiler.py", line 275, in query_vcvarsall
    stderr=subprocess.PIPE)
  File "C:\python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xed' in position 15:
 ordinal not in range(128)
```

**Comment by jeffwidman** [comment]
At first glance, this looks like a `distutils` / `setuptools` bug, not a `markupsafe` bug.
