### ISSUE TITLE
AssertionError while building wheel on 3.5

### ISSUE THREAD

**Issue by miedzinski** [pallets/markupsafe#51]
Installing `markupsafe` 0.23 on Python 3.5 results in AssertionError when building wheel. 3.4 is fine.

```
$ python -c 'import sys; print(sys.version_info)'
sys.version_info(major=3, minor=5, micro=1, releaselevel='final', serial=0)
$ pip install markupsafe
Collecting markupsafe
  Using cached MarkupSafe-0.23.tar.gz
Building wheels for collected packages: markupsafe
  Running setup.py bdist_wheel for markupsafe
  Complete output from command /home/dominik/.virtualenvs/markupsafe/bin/python3.5 -c "import setuptools;__file__='/tmp/pip-build-dsnw5xme/markupsafe/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpujl60qh6pip-wheel-:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.5
  creating build/lib.linux-x86_64-3.5/markupsafe
  copying markupsafe/tests.py -> build/lib.linux-x86_64-3.5/markupsafe
  copying markupsafe/_compat.py -> build/lib.linux-x86_64-3.5/markupsafe
  copying markupsafe/_native.py -> build/lib.linux-x86_64-3.5/markupsafe
  copying markupsafe/__init__.py -> build/lib.linux-x86_64-3.5/markupsafe
  copying markupsafe/_constants.py -> build/lib.linux-x86_64-3.5/markupsafe
  running egg_info
  writing MarkupSafe.egg-info/PKG-INFO
  writing top-level names to MarkupSafe.egg-info/top_level.txt
  writing dependency_links to MarkupSafe.egg-info/dependency_links.txt
  warning: manifest_maker: standard file '-c' not found
  
  reading manifest file 'MarkupSafe.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'MarkupSafe.egg-info/SOURCES.txt'
  copying markupsafe/_speedups.c -> build/lib.linux-x86_64-3.5/markupsafe
  running build_ext
  building 'markupsafe._speedups' extension
  creating build/temp.linux-x86_64-3.5
  creating build/temp.linux-x86_64-3.5/markupsafe
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -I/home/dominik/.virtualenvs/markupsafe/include/python3.5m -c markupsafe/_speedups.c -o build/temp.linux-x86_64-3.5/markupsafe/_speedups.o
  x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.5/markupsafe/_speedups.o -o build/lib.linux-x86_64-3.5/markupsafe/_speedups.cpython-35m-x86_64-linux-gnu.so
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.linux-x86_64
  creating build/bdist.linux-x86_64/wheel
  creating build/bdist.linux-x86_64/wheel/markupsafe
  copying build/lib.linux-x86_64-3.5/markupsafe/tests.py -> build/bdist.linux-x86_64/wheel/markupsafe
  copying build/lib.linux-x86_64-3.5/markupsafe/_compat.py -> build/bdist.linux-x86_64/wheel/markupsafe
  copying build/lib.linux-x86_64-3.5/markupsafe/_native.py -> build/bdist.linux-x86_64/wheel/markupsafe
  copying build/lib.linux-x86_64-3.5/markupsafe/__init__.py -> build/bdist.linux-x86_64/wheel/markupsafe
  copying build/lib.linux-x86_64-3.5/markupsafe/_speedups.c -> build/bdist.linux-x86_64/wheel/markupsafe
  copying build/lib.linux-x86_64-3.5/markupsafe/_constants.py -> build/bdist.linux-x86_64/wheel/markupsafe
  copying build/lib.linux-x86_64-3.5/markupsafe/_speedups.cpython-35m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/wheel/markupsafe
  running install_egg_info
  Copying MarkupSafe.egg-info to build/bdist.linux-x86_64/wheel/MarkupSafe-0.23-py3.5.egg-info
  running install_scripts
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-dsnw5xme/markupsafe/setup.py", line 120, in <module>
      try_building_extension()
    File "/tmp/pip-build-dsnw5xme/markupsafe/setup.py", line 99, in try_building_extension
      run_setup(True)
    File "/tmp/pip-build-dsnw5xme/markupsafe/setup.py", line 93, in run_setup
      ext_modules=ext_modules,
    File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/dominik/.virtualenvs/markupsafe/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 213, in run
      archive_basename = self.get_archive_basename()
    File "/home/dominik/.virtualenvs/markupsafe/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 161, in get_archive_basename
      impl_tag, abi_tag, plat_tag = self.get_tag()
    File "/home/dominik/.virtualenvs/markupsafe/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 155, in get_tag
      assert tag == supported_tags[0]
  AssertionError
  
  ----------------------------------------
  Failed building wheel for markupsafe
Failed to build markupsafe
Installing collected packages: markupsafe
  Running setup.py install for markupsafe
Successfully installed markupsafe-0.23
```

**Comment by rubendibattista** [comment]
+ 1

**Comment by davidism** [comment]
I can't replicate this issue based on the information provided.  Try upgrading the setuptools and wheel packages or clearing pip's cache.  If you are still having this issue, please post more information.

**Comment by sivang** [comment]
@davidism you were right, upgrading the wheel version solves this. Thanks.
