### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by MartinBrugnara** [pallets/markupsafe#59]
pip install MarkupSafe

Issue: _Successfully installed_ even though something _Failed_
How to reproduce: `pip install MarkupSafe`

Python version: 3.5.1

```
 running install_egg_info
  Copying MarkupSafe.egg-info to build/bdist.macosx-10.11-x86_64/wheel/MarkupSafe-0.23-py3.5.egg-info
 running install_scripts
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/s_/8qs7_w993rvbqpr1x580j8_40000gn/T/pip-build-q6aenb1b/MarkupSafe/setup.py", line 120, in <module>
      try_building_extension()
    File "/private/var/folders/s_/8qs7_w993rvbqpr1x580j8_40000gn/T/pip-build-q6aenb1b/MarkupSafe/setup.py", line 99, in try_building_extension
      run_setup(True)
    File "/private/var/folders/s_/8qs7_w993rvbqpr1x580j8_40000gn/T/pip-build-q6aenb1b/MarkupSafe/setup.py", line 93, in run_setup
      ext_modules=ext_modules,
    File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/Users/martin/Projects/xplainbox-wrapper-hdfs/.venv/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 213, in run
      archive_basename = self.get_archive_basename()
    File "/Users/martin/Projects/xplainbox-wrapper-hdfs/.venv/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 161, in get_archive_basename
      impl_tag, abi_tag, plat_tag = self.get_tag()
    File "/Users/martin/Projects/xplainbox-wrapper-hdfs/.venv/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 155, in get_tag
      assert tag == supported_tags[0]
  AssertionError
  ----------------------------------------
  Failed building wheel for MarkupSafe
  Running setup.py clean for MarkupSafe
Failed to build MarkupSafe
Installing collected packages: MarkupSafe
  Running setup.py install for MarkupSafe ... done
Successfully installed MarkupSafe-0.23
```

**Comment by davidism** [comment]
Make sure `setuptools`, `pip`, and `wheel` are up to date in your env.  `pip install -U pip setuptools wheel`

**Comment by MartinBrugnara** [comment]
Thank you!
I confirm `wheel` version was the problem.
